stages:
  - init
  - build
  - test

default:
  image: trion/ng-cli-karma

init_depedences:
  stage: init
  artifacts:
    paths:
      - node_modules/
  script:
    - npm ci

build_front:
  stage: build
  script:
    - npm run build:prod

testing_front:
  stage: test
  script:
    - npm run test:ci
