default:
  image: trion/ng-cli-karma

init_depedences:
  stage: .pre
  script:
    - npm ci

build_front:
  stage: build
  script:
    - npm run build:prod

testing_front:
  stage: test
  script:
    - npm run test:ci
